#!/usr/bin/env python3
# Generate the LaTeX table of Compressor concurrent-compaction results
# (runtime and mean GC pause) from the GC benchmark records.
#
# Usage:
#   ./print_gc_table.py
#   ./print_gc_table.py -r ../results/gc -o ../figures/gc_table.tex

import argparse
import glob
import json
import os
import statistics
import sys
from collections import defaultdict

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_RESULTS = os.path.join(SCRIPT_DIR, "../results/gc")
DEFAULT_OUTPUT = os.path.join(SCRIPT_DIR, "../figures/gc_table.tex")

# Benchmarks in table order, at 1.5x each one's minimum heap
BENCHES = ["h2", "pmd", "xalan", "lusearch"]
CONFIGS = [("None", "STW"), ("Uffd", r"\uffd"), ("R1", r"\name")]


def collect(results_dir):
    """(bench, config) -> {"time_s": [...], "pause_ms": [...]}"""
    out = defaultdict(lambda: {"time_s": [], "pause_ms": []})
    files = sorted(glob.glob(
        os.path.join(results_dir, "gc_benchmark_classB_*.json")))
    if not files:
        sys.exit(f"error: no class B records in {results_dir}")
    for path in files:
        with open(path) as f:
            records = json.load(f)
        for r in records:
            res = r["results"]
            if not res.get("passed"):
                continue
            key = (r["bench"], r["config"])
            if r["kind"] == "throughput" and res.get("last_iter_ms"):
                out[key]["time_s"].append(res["last_iter_ms"] / 1000)
            elif r["kind"] == "pauses" and res.get("pause_avg_us"):
                out[key]["pause_ms"].append(res["pause_avg_us"] / 1000)
    return out


def fmt(vals, unit):
    if not vals:
        return "--"
    mean = statistics.mean(vals)
    return (f"{mean:.1f}\\,s" if unit == "s" else f"{mean:.0f}\\,ms")


def main():
    ap = argparse.ArgumentParser(
        description="Generate the concurrent-compaction LaTeX table")
    ap.add_argument("-r", "--results-dir", default=DEFAULT_RESULTS)
    ap.add_argument("-o", "--output", default=DEFAULT_OUTPUT)
    args = ap.parse_args()

    data = collect(args.results_dir)

    missing = [f"{b}/{c}" for b in BENCHES for c, _ in CONFIGS
               if not data[(b, c)]["time_s"] or not data[(b, c)]["pause_ms"]]
    if missing:
        print(f"warning: no complete records for {', '.join(missing)}",
              file=sys.stderr)

    lines = [
        r"% Generated by print_gc_table.py -- do not edit by hand.",
        r"\begin{table}[!t]",
        r"\centering",
        r"\footnotesize",
        r"\begin{tabular}{l rr rr rr}",
        r"\toprule",
        r" & \multicolumn{2}{c}{STW} & \multicolumn{2}{c}{\uffd}"
        r" & \multicolumn{2}{c}{\name} \\",
        r"\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}",
        r"\textbf{Workload} & \textbf{Time} & \textbf{Pause}"
        r" & \textbf{Time} & \textbf{Pause}"
        r" & \textbf{Time} & \textbf{Pause} \\",
        r"\midrule",
    ]
    for bench in BENCHES:
        cells = []
        for config, _ in CONFIGS:
            d = data[(bench, config)]
            cells.append(fmt(d["time_s"], "s"))
            cells.append(fmt(d["pause_ms"], "ms"))
        lines.append(f"{bench} & " + " & ".join(cells) + r" \\")
    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\caption{Concurrent compaction: runtime and mean GC pause.}",
        r"\label{tab:gc-compaction}",
        r"\vspace{-3em}",
        r"\end{table}",
    ]

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, "w") as f:
        f.write("\n".join(lines) + "\n")

    # Plain-text summary to stderr
    hdr = f"{'Workload':<10s}" + "".join(
        f"{label + ' time':>12s}{label + ' pause':>13s}"
        for _, label in [(c, l.lstrip(chr(92))) for c, l in CONFIGS])
    print(hdr, file=sys.stderr)
    print("─" * len(hdr), file=sys.stderr)
    for bench in BENCHES:
        row = f"{bench:<10s}"
        for config, _ in CONFIGS:
            d = data[(bench, config)]
            t = f"{statistics.mean(d['time_s']):.1f}s" if d["time_s"] else "--"
            p = (f"{statistics.mean(d['pause_ms']):.0f}ms"
                 if d["pause_ms"] else "--")
            row += f"{t:>12s}{p:>13s}"
        print(row, file=sys.stderr)
    print(f"LaTeX table written to {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
