#!/usr/bin/env python3
# Generate the GenImmix dirty-tracking comparison (steady-state iteration
# time per backend, relative to the compiled write barrier) from the GC
# benchmark records. These numbers are quoted in the text of the garbage
# collection evaluation rather than printed as a numbered table.
#
# Usage:
#   ./print_gc_dirty_table.py
#   ./print_gc_dirty_table.py -r ../results/gc -o ../figures/gc_dirty_table.tex

import argparse
import glob
import json
import os
import statistics
import sys
from collections import defaultdict

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_RESULTS = os.path.join(SCRIPT_DIR, "../results/gc")
DEFAULT_OUTPUT = os.path.join(SCRIPT_DIR, "../figures/gc_dirty_table.tex")

BENCHES = ["h2", "pmd", "xalan", "lusearch"]
BASELINE = "Barrier"
# Page-protection backends, in the order the text introduces them
BACKENDS = [("Segv", "SIGSEGV"), ("Uffd", r"\uffd"), ("Bpf", r"\name")]


def collect(results_dir):
    """(bench, config) -> [steady-state iteration time in seconds]"""
    out = defaultdict(list)
    files = sorted(glob.glob(
        os.path.join(results_dir, "gc_benchmark_classA_*.json")))
    if not files:
        sys.exit(f"error: no class A records in {results_dir}")
    for path in files:
        with open(path) as f:
            records = json.load(f)
        for r in records:
            res = r["results"]
            if r["kind"] != "throughput" or not res.get("passed"):
                continue
            if res.get("last_iter_ms"):
                out[(r["bench"], r["config"])].append(
                    res["last_iter_ms"] / 1000)
    return out


def main():
    ap = argparse.ArgumentParser(
        description="Generate the dirty-tracking comparison table")
    ap.add_argument("-r", "--results-dir", default=DEFAULT_RESULTS)
    ap.add_argument("-o", "--output", default=DEFAULT_OUTPUT)
    args = ap.parse_args()

    data = collect(args.results_dir)

    def mean(bench, config):
        vals = data[(bench, config)]
        return statistics.mean(vals) if vals else None

    lines = [
        r"% Generated by print_gc_dirty_table.py -- do not edit by hand.",
        r"\begin{table}[!t]",
        r"\centering",
        r"\footnotesize",
        r"\begin{tabular}{l r rr rr rr}",
        r"\toprule",
        r" & \textbf{Barrier} & \multicolumn{2}{c}{\textbf{SIGSEGV}}"
        r" & \multicolumn{2}{c}{\uffd} & \multicolumn{2}{c}{\name} \\",
        r"\cmidrule(lr){3-4} \cmidrule(lr){5-6} \cmidrule(lr){7-8}",
        r"\textbf{Workload} & \textbf{Time} & \textbf{Time} & \textbf{$\Delta$}"
        r" & \textbf{Time} & \textbf{$\Delta$}"
        r" & \textbf{Time} & \textbf{$\Delta$} \\",
        r"\midrule",
    ]
    # Ranges quoted in the prose, over the benchmarks where the barrier wins
    deltas = defaultdict(list)
    for bench in BENCHES:
        base = mean(bench, BASELINE)
        cells = ["--" if base is None else f"{base:.1f}\\,s"]
        for config, _ in BACKENDS:
            val = mean(bench, config)
            if val is None or base is None:
                cells += ["--", "--"]
                continue
            pct = (val / base - 1) * 100
            cells += [f"{val:.1f}\\,s", f"{pct:+.0f}\\%"]
            if pct > 0:
                deltas[config].append(pct)
        lines.append(f"{bench} & " + " & ".join(cells) + r" \\")
    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\caption{GenImmix dirty tracking: steady-state iteration time and"
        r" its change relative to the compiled write barrier.}",
        r"\label{tab:gc-dirty-tracking}",
        r"\end{table}",
    ]

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, "w") as f:
        f.write("\n".join(lines) + "\n")

    # Plain-text summary to stderr, in the shape the text quotes
    hdr = (f"{'Workload':<10s}{'Barrier':>10s}" +
           "".join(f"{name:>10s}{'Δ':>8s}" for _, name in
                   [(c, c) for c, _ in BACKENDS]))
    print(hdr, file=sys.stderr)
    print("─" * len(hdr), file=sys.stderr)
    for bench in BENCHES:
        base = mean(bench, BASELINE)
        row = f"{bench:<10s}" + (f"{base:>9.1f}s" if base else f"{'--':>10s}")
        for config, _ in BACKENDS:
            val = mean(bench, config)
            if val is None or base is None:
                row += f"{'--':>10s}{'--':>8s}"
            else:
                row += f"{val:>9.1f}s{(val / base - 1) * 100:>+7.0f}%"
        print(row, file=sys.stderr)
    print("", file=sys.stderr)
    for config, _ in BACKENDS:
        if deltas[config]:
            print(f"  {config} slows the benchmarks it loses on by "
                  f"{min(deltas[config]):.0f}--{max(deltas[config]):.0f}%",
                  file=sys.stderr)
    base, best = mean("xalan", BASELINE), mean("xalan", "Bpf")
    if base and best:
        print(f"  xalan: page-based tracking is {base / best:.1f}x faster "
              f"than the barrier", file=sys.stderr)
    print(f"LaTeX table written to {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
